# services:
  # 1. 데이터베이스 (MariaDB) : docker image 설정 제거
  # RDS사용

  # 2. 백엔드 (Spring Boot) : ECR 활용 설정
services:
  backend:
    build: ./backend  # 이 줄이 있어야 'build' 명령어가 동작합니다.
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/yj-backend:latest
    container_name: yj-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=${DB_USERNAME}    # EC2 환경변수에서 주입
      - DB_PASSWORD=${DB_PASSWORD}    # EC2 환경변수에서 주입
    ports:
      - "8080:8080"

  # 3. 프론트엔드 (React) : ECR 활용 설정
  frontend:
    build: ./frontend  # 이 줄을 추가해야 로컬에서 이미지를 빌드합니다.
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/yj-frontend:latest
    container_name: yj-frontend
    ports:
      - "63342:80"
